### ISSUE TITLE
Error: usb.core.USBError: [Errno 19] No such device (it may have been disconnected)

### ISSUE THREAD

**Issue by ExeRhythm** [pixelomer/PongoBRIX#3]
Hi again, I get this error when running `make load_brix` in PongoBRIX directory:
```
python3 /Users/exerhythm/pongoOS/scripts/upload_data.py brix.bin
Traceback (most recent call last):
  File "/Users/exerhythm/pongoOS/scripts/upload_data.py", line 31, in <module>
    dev.set_configuration()
  File "/opt/homebrew/lib/python3.9/site-packages/usb/core.py", line 905, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/opt/homebrew/lib/python3.9/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/usb/core.py", line 159, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/opt/homebrew/lib/python3.9/site-packages/usb/backend/libusb1.py", line 812, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/opt/homebrew/lib/python3.9/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)
make: *** [Makefile:15: load_brix] Error 1
```

My Makefile is:
```
brix.bin: main.c Makefile chip8.h chip8.c
	xcrun -sdk iphoneos gcc main.c chip8.c -o brix.bin -fno-stack-protector -arch arm64 -mabi=aapcs -Xlinker -kext -nostdlib -Xlinker -fatal_warnings -D_SECURE__STRING_H_ -O3

button_helper.bin: button_helper.c Makefile
	xcrun -sdk iphoneos gcc button_helper.c -o button_helper.bin -fno-stack-protector -arch arm64 -mabi=aapcs -Xlinker -kext -nostdlib -Xlinker -fatal_warnings -D_SECURE__STRING_H_ -O3

clean:
	rm -f brix.bin

load_brix: brix.bin
	python3 /Users/exerhythm/pongoOS/scripts/upload_data.py brix.bin
	(printf 'modload\n'; cat) | (/Users/exerhythm/pongoOS/scripts/pongoterm || true)

load_buttons: button_helper.bin
	python3 /Users/exerhythm/pongoOS/scripts/upload_data.py button_helper.bin
	(printf 'modload\n'; cat) | (/Users/exerhythm/pongoOS/scripts/pongoterm || true)

```

Do you know how to fix this? Thanks in advance

**Comment by ExeRhythm** [comment]
Tried switching to Python version 3.8 and now I am getting this error:
```
exerhythm@Matvejs-MacBook-Air PongoBRIX % make load_brix       
python3.8 /Users/exerhythm/pongoOS/scripts/upload_data.py brix.bin
Traceback (most recent call last):
  File "/Users/exerhythm/pongoOS/scripts/upload_data.py", line 28, in <module>
    dev = usb.core.find(idVendor=0x05ac, idProduct=0x4141)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/core.py", line 1299, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
make: *** [Makefile:15: load_brix] Error 1

```

**Comment by pixelomer** [comment]
Make sure you installed libusb. You can install it using MacPorts or Homebrew.

**Comment by ExeRhythm** [comment]
I have it already installed

**Comment by ExeRhythm** [comment]
```
Warning: libusb 1.0.24 is already installed and up-to-date.
To reinstall 1.0.24, run:
  brew reinstall libusb
exerhythm@Matvejs-MacBook-Air PongoBRIX % make load_brix     
python3.8 /Users/exerhythm/pongoOS/scripts/upload_data.py brix.bin
Traceback (most recent call last):
  File "/Users/exerhythm/pongoOS/scripts/upload_data.py", line 28, in <module>
    dev = usb.core.find(idVendor=0x05ac, idProduct=0x4141)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/core.py", line 1299, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
make: *** [Makefile:15: load_brix] Error 1
exerhythm@Matvejs-MacBook-Air PongoBRIX % 

```

**Comment by pixelomer** [comment]
Can you try uninstalling and reinstalling both Python and libusb using Homebrew? Also make sure you are using the Homebrew build of Python.

**Comment by ExeRhythm** [comment]
Thanks for replying. Sadly, the issue still persists

**Comment by ExeRhythm** [comment]
It works now. I don't know what I have done, but it works! Thanks
